### ISSUE TITLE
Question: is this fork of deepspeed runnable on nvidia gpus?

### ISSUE THREAD

**Issue by awan-10** [ROCmSoftwarePlatform/DeepSpeed#15]
Hi @jithunnair-amd, I am just curious to learn a bit more about this fork of deepspeed. 

Can this run fine on a machine with an NVIDIA GPU like A100? Also, is the ROCM code portable so it can run on AMD or NVIDIA GPU without any changes needed?

Any special dependencies or readme file that I can look for?

**Comment by jithunnair-amd** [comment]
Hi @awan-10, we have not really tested this fork of DeepSpeed on Nvidia GPUs, as this is meant to be for enabling DeepSpeed on ROCm, so I cannot give a definitive answer to your questions right now. I would say that I expect most of the changes so far to be portable so it can run on AMD or Nvidia GPUs.

As for the dependencies, they are essentially the same; you just need to make sure that they have ROCm support eg. torch, torchvision and apex. We provide a [Dockerfile.rocm](https://github.com/ROCmSoftwarePlatform/DeepSpeed/blob/master/docker/Dockerfile.rocm) and docker images at https://hub.docker.com/r/rocm/deepspeed/tags

**Comment by awan-10** [comment]
Thanks. I will try things out then.
