### ISSUE TITLE
Error happened when executing "DS_BUILD_CPU_ADAM=1 python setup.py bdist_wheel"

### ISSUE THREAD

**Issue by zjx19951012** [ROCmSoftwarePlatform/DeepSpeed#46]
Hello,
I am trying to build wheel for ROCM4.0.1, and here is the error.

==============================================================================
`NOTE: Please manually install torch and torchvision packages for ROCm
DS_BUILD_OPS=0
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/StopWatch.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/StopWatch.h ok
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/Timer.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/Timer_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/cublas_wrappers.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/cublas_wrappers_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/gemm_test.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/gemm_test_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/context.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/context_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/dropout.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/dropout_hip.h skipped
Failed to save /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_cooperative_groups_helper_hip.h with "Permission denied", leaving /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_cooperative_groups_helper.h unchanged.
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_cooperative_groups_helper.h -> /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_cooperative_groups_helper.h skipped
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_cooperative_groups.h -> /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_cooperative_groups.h ok
Failed to save /public/software/compiler/rocm/rocm-4.0.1/include/hip/nvcc_detail/hip_cooperative_groups_hip.h with "Permission denied", leaving /public/software/compiler/rocm/rocm-4.0.1/include/hip/nvcc_detail/hip_cooperative_groups.h unchanged.
/public/software/compiler/rocm/rocm-4.0.1/include/hip/nvcc_detail/hip_cooperative_groups.h -> /public/software/compiler/rocm/rocm-4.0.1/include/hip/nvcc_detail/hip_cooperative_groups.h skipped
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hip_cooperative_groups.h -> /public/software/compiler/rocm/rocm-4.0.1/include/hip/hip_cooperative_groups.h ok
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/custom_cuda_layers.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/custom_hip_layers.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/feed_forward.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/feed_forward_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/gelu.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/gelu_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/general_kernels.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/general_kernels_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/normalize_layer.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/normalize_layer_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/softmax.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/softmax_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/strided_batch_gemm.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/strided_batch_gemm_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/ds_transformer_cuda.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/ds_transformer_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/gelu.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/gelu_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/general_kernels.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/general_kernels_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/normalize_layer.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/normalize_layer_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/quantizer.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/quantizer_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/softmax.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/softmax_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/strided_batch_gemm.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/strided_batch_gemm_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/cublas_wrappers_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/dropout_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/general_kernels_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/normalize_layer_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/softmax_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/cpu_adam_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/cpu_adam.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/cpu_adam_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/cublas_wrappers.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/cublas_wrappers_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/custom_cuda_layers.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/custom_hip_layers.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/feed_forward.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/feed_forward_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/gemm_test.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/gemm_test_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/type_shim.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/type_shim_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/Timer_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/gemm_test_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/context_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/custom_hip_layers.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/feed_forward_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/gelu_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/strided_batch_gemm_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/ds_transformer_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/quantizer_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/type_shim_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups_helper.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups_helper_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups_helper_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups.h -> /public/home/zhujingxu/DeepSpeed-master/csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups_hip.h skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups_hip.h -> None ignored
/public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam.cpp -> /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp skipped
/public/home/zhujingxu/DeepSpeed-master/csrc/adam/custom_cuda_kernel.cu -> /public/home/zhujingxu/DeepSpeed-master/csrc/adam/custom_hip_kernel.hip skipped
Successfully preprocessed all matching files.
Total number of unsupported CUDA function calls: 0

Total number of replaced kernel launches: 1
 [WARNING]  sparse_attn cuda is not available from torch
Install Ops={'cpu_adam': 1, 'fused_adam': False, 'fused_lamb': False, 'sparse_attn': False, 'transformer': False, 'stochastic_transformer': False, 'async_io': False, 'transformer_inference': False, 'utils': False, 'quantizer': False}
fatal: Not a git repository (or any parent up to mount point /public)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
version=0.4.6+unknown, git_hash=unknown, git_branch=unknown
install_requires=['#torch>=1.2', '#torchvision>=0.4.0', 'tqdm', 'tensorboardX==1.8', 'ninja', 'numpy', 'psutil']
compatible_ops={'cpu_adam': True, 'fused_adam': True, 'fused_lamb': True, 'sparse_attn': False, 'transformer': True, 'stochastic_transformer': True, 'async_io': True, 'transformer_inference': True, 'utils': True, 'quantizer': True}
ext_modules=[<setuptools.extension.Extension('deepspeed.ops.adam.cpu_adam_op') at 0x2af313727b90>]
running bdist_wheel
running build
running build_py
copying deepspeed/git_version_info_installed.py -> build/lib.linux-x86_64-3.7/deepspeed
running build_ext
building 'deepspeed.ops.adam.cpu_adam_op' extension
gcc -pthread -B /public/home/zhujingxu/miniconda3/envs/ds/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/includes -I/public/software/compiler/rocm/rocm-4.0.1/include -I/public/software/compiler/rocm/rocm-4.0.1/include/rocrand -I/public/software/compiler/rocm/rocm-4.0.1/include/hiprand -I/public/home/zhujingxu/miniconda3/envs/ds/lib/python3.7/site-packages/torch/include -I/public/home/zhujingxu/miniconda3/envs/ds/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/public/home/zhujingxu/miniconda3/envs/ds/lib/python3.7/site-packages/torch/include/TH -I/public/home/zhujingxu/miniconda3/envs/ds/lib/python3.7/site-packages/torch/include/THC -I/public/home/zhujingxu/miniconda3/envs/ds/lib/python3.7/site-packages/torch/include/THH -I/public/software/compiler/rocm/rocm-4.0.1/include -I/public/software/compiler/rocm/rocm-4.0.1/miopen/include -I/public/home/zhujingxu/miniconda3/envs/ds/include/python3.7m -c /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp -o build/temp.linux-x86_64-3.7/public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.o -fPIC -D__HIP_PLATFORM_HCC__=1 -O3 -std=c++14 -L/public/software/compiler/rocm/rocm-4.0.1/lib -lcudart -lcublas -g -Wno-reorder -march=native -fopenmp -D__SCALAR__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=cpu_adam_op -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_kernel.h:35:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel_hcc.h:37,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel.h:54,
                 from csrc/includes/custom_hip_layers.h:14,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:14:
/public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_uniform.h: In function ‘__half rocrand_device::detail::uniform_distribution_half(short unsigned int)’:
/public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_uniform.h:123:70: error: call of overloaded ‘__float2half(float)’ is ambiguous
     return __float2half(ROCRAND_2POW16_INV + (v * ROCRAND_2POW16_INV));
                                                                      ^
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16.h:1657:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hip_fp16.h:29,
                 from csrc/includes/cpu_adam_hip.h:9,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:2:
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:19:12: note: candidate: __half __float2half(float)
     __half __float2half(float);
            ^~~~~~~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:142:16: note: candidate: __half {anonymous}::__float2half(float)
         __half __float2half(float x)
                ^~~~~~~~~~~~
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_kernel.h:36:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel_hcc.h:37,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel.h:54,
                 from csrc/includes/custom_hip_layers.h:14,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:14:
/public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_normal.h: In function ‘__half2 rocrand_device::detail::box_muller_half(short unsigned int, short unsigned int)’:
/public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_normal.h:112:25: error: call of overloaded ‘__float2half(hip_impl::Scalar_accessor<float, float [2], 0>&)’ is ambiguous
         __float2half(r.x),
                         ^
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16.h:1657:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hip_fp16.h:29,
                 from csrc/includes/cpu_adam_hip.h:9,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:2:
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:19:12: note: candidate: __half __float2half(float)
     __half __float2half(float);
            ^~~~~~~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:142:16: note: candidate: __half {anonymous}::__float2half(float)
         __half __float2half(float x)
                ^~~~~~~~~~~~
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_kernel.h:36:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel_hcc.h:37,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel.h:54,
                 from csrc/includes/custom_hip_layers.h:14,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:14:
/public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_normal.h:113:25: error: call of overloaded ‘__float2half(hip_impl::Scalar_accessor<float, float [2], 1>&)’ is ambiguous
         __float2half(r.y)
                         ^
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16.h:1657:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hip_fp16.h:29,
                 from csrc/includes/cpu_adam_hip.h:9,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:2:
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:19:12: note: candidate: __half __float2half(float)
     __half __float2half(float);
            ^~~~~~~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:142:16: note: candidate: __half {anonymous}::__float2half(float)
         __half __float2half(float x)
                ^~~~~~~~~~~~
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_kernel.h:36:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel_hcc.h:37,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hiprand/hiprand_kernel.h:54,
                 from csrc/includes/custom_hip_layers.h:14,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:14:
/public/software/compiler/rocm/rocm-4.0.1/include/rocrand/rocrand_normal.h:114:5: error: no matching function for call to ‘__half2::__half2(<brace-enclosed initializer list>)’
     };
     ^
In file included from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16.h:1657:0,
                 from /public/software/compiler/rocm/rocm-4.0.1/include/hip/hip_fp16.h:29,
                 from csrc/includes/cpu_adam_hip.h:9,
                 from /public/home/zhujingxu/DeepSpeed-master/csrc/adam/cpu_adam_hip.cpp:2:
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:75:9: note: candidate: constexpr __half2::__half2(__half2&&)
         __half2(__half2&&) = default;
         ^~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:75:9: note:   candidate expects 1 argument, 2 provided
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:74:9: note: candidate: constexpr __half2::__half2(const __half2&)
         __half2(const __half2&) = default;
         ^~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:74:9: note:   candidate expects 1 argument, 2 provided
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:73:9: note: candidate: __half2::__half2(const __half&, const __half&)
         __half2(const __half& ix, const __half& iy) : x{ix}, y{iy} {}
         ^~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:73:9: note:   conversion of argument 1 would be ill-formed:
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:68:9: note: candidate: __half2::__half2(const __half2_raw&)
         __half2(const __half2_raw& ix)
         ^~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:68:9: note:   candidate expects 1 argument, 2 provided
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:67:9: note: candidate: __half2::__half2()
         __half2() = default;
         ^~~~~~~
/public/software/compiler/rocm/rocm-4.0.1/include/hip/hcc_detail/hip_fp16_gcc.h:67:9: note:   candidate expects 0 arguments, 2 provided
error: command 'gcc' failed with exit status 1`

=================================================================================
I have already built the virtual conda environment with rocm-4.0.1, pytorch-rocm, and cupy-rocm. 
Anyone encounter with the similar issue, please help out. Thanks!

**Comment by hanjiemicro** [comment]
I met the same error with rocm-4.0.
 @zjx19951012 Any idea?
